# Generated by Django 5.2.3 on 2025-07-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('doctorId', models.IntegerField(max_length=20)),
                ('age', models.IntegerField()),
                ('department', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='national_id',
            new_name='national_ID',
        ),
    ]
