# Generated by Django 5.2.3 on 2025-07-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_doctor_rename_national_id_patient_national_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(max_length=100)),
                ('floor', models.IntegerField()),
                ('department', models.CharField(max_length=20)),
                ('Head_nurse', models.CharField(max_length=20)),
            ],
        ),
    ]
